import './styles.scss';
import './js/defaultLoadLocal';
import './js/modal-authorization';
import './js/logOut';
import './js/firstLoad';
import './js/oneCardFetch';
import './js/renderSingleCard';
import './js/top-buttons.js';
import './js/paginationLogic';
